---
swagger: '2.0'
info:
  description: Component management API
  version: '1.0'
  title: component-mgmt
  termsOfService: urn:tos
  contact: {}
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0
schemes:
  - https
produces:
  - application/json
basePath: "/"
tags:
- name: basic-error-controller
  description: Basic Error Controller
- name: component-controller
  description: Component Controller
- name: component-type-controller
  description: Component Type Controller
- name: component-version-action-controller
  description: Component Version Action Controller
- name: component-version-controller
  description: Component Version Controller
- name: component-version-reference-controller
  description: Component Version Reference Controller
- name: main-controller
  description: Main Controller
- name: operation-handler
  description: Operation Handler
- name: web-mvc-links-handler
  description: Web Mvc Links Handler
#securityDefinitions:
#    google_id_token:
#      authorizationUrl: ""
#      flow: "implicit"
#      type: "oauth2"
#      x-google-issuer: "https://accounts.google.com"
#      x-google-jwks_uri: "https://www.googleapis.com/oauth2/v3/certs"
#      # Optional. Replace YOUR-CLIENT-ID with your client ID
#      x-google-audiences: "1013327549262-gbol2nhr4214st783icjj0lik6hr8u18.apps.googleusercontent.com"
#security:
#    - google_id_token: []
paths:
  "/":
    get:
      tags:
      - main-controller
      summary: homePage
      operationId: homePageUsingGET
      x-google-backend:
        address: https://gke-learning-4caf.oa.r.appspot.com/
        jwt_audience: 1013327549262-gbol2nhr4214st783icjj0lik6hr8u18.apps.googleusercontent.com
      produces:
      - "*/*"
      responses:
        '200':
          description: OK
          schema:
            type: string
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
 